# fly.toml app configuration file generated for guildapp on 2024-01-11T10:24:22+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "guildapp"
primary_region = "otp"

[build]
  image = "arkhenrei/guildapp"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "295836768725698"
  CloudinarySettings__CloudName = "dkxdtjvgy"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
